export const ENV_KEYS = {
  DATABASE_URL: "DATABASE_URL",
  DIRECT_URL: "DIRECT_URL",
  JWT_ACCESS_EXPIRES_IN: "JWT_ACCESS_EXPIRES_IN",
  JWT_ACCESS_SECRET: "JWT_ACCESS_SECRET",
  JWT_REFRESH_EXPIRES_IN: "JWT_REFRESH_EXPIRES_IN",
  JWT_REFRESH_SECRET: "JWT_REFRESH_SECRET",
  OTP_EXPIRES_MINUTES: "OTP_EXPIRES_MINUTES",
  RESEND_API_KEY: "RESEND_API_KEY",
  RESEND_FROM_EMAIL: "RESEND_FROM_EMAIL",
  SUPABASE_ANON: "SUPABASE_ANON",
  SUPABASE_SERVICE_ROLE_KEY: "SUPABASE_SERVICE_ROLE_KEY",
  SUPABASE_URL: "SUPABASE_URL",
} as const;
